language: node_js
stages:
- test
- name: deploy
  if: branch = master
jobs:
  include:
  - stage: test
    install: true
    script:
    - echo 'tests here'
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
notifications:
  slack:
    secure: wTB8Da8OAV23oMaZrjV9KrPiErP4ZBb8vBaOlwEC7hxOVN9jvklvzeD9Wq+PKc0GnHzjms29Awo3pM2oFyCSrkGOQxe/62uNd39WpSCIXVxcqrx2881yO/CMssjD+KV9zDu7nYUat2uZjeZh7R2l5W1yW/TV89ro3TMMxMstxHJI6rhOFQFWMassomPjgeXOweoJtfRqeeGLyGyoMEhCRrt2oQV21woUWeUlhkNUR5Nv+Nodax24iFpS9BLFEipG8RuWM2iA/ocM2Qbd8Z3z94Y5O164nYpSM4GZHmvaAJebCCiq61FkQDXJusToDWBJ0qPvnQ+CFJs1pTL9ngqpbYl1Ptzq8C+U/lCCizyKIbqXcEF3Yc9wR7LS6RNq5khvj6u3okomgvXDiST8hF9npsAV/7xjP47DalJDoq2iBlM/FsawPxflZ0FKX1MFcJ4aK4a9Etrtja6trpd+15PdghDBA1hDlD0BmJu8NjpazOhOD6Cnz0Kn3cY8ZQbP5YDYhiQHCVTzPSeCgx3D/MkZqcRIhzVLQt8pbFGOHsMIpG2x3YQrVEq5uNgpVugtnzfmBItrhqe0Ew2AijdBLX6onN+kD4fr0KLBNWhP70RiWLSm79VFZNB05XM2BQSsshaF4yb/kB1h4AV30ta4yfA/gidDnFfrle9LxsKZ1Kp969c=
